-- ============================================================
-- Migración 000 — Bootstrap de tablas LEGACY (solo para entornos limpios / QA)
-- ------------------------------------------------------------
-- En producción, las tablas `app_users`, `leads`, `appointments` y
-- `activity_events` (más sus ENUMs) fueron creadas a mano por el técnico
-- anterior y NUNCA quedaron como migración. Las migraciones 005/006/007
-- asumen que ya existen, por lo que un proyecto Supabase NUEVO falla.
--
-- Esta migración recrea ese estado base de forma idempotente, en su versión
-- "pre-006/007": `appointments` SIN campus_id (lo agrega 006) y `leads` SIN
-- child_grade (lo agrega 007), para que la cadena de migraciones siga válida.
--
-- Esquema extraído de producción (rugchqrjuxjqhdcfohby) el 2026-06-18.
-- ============================================================

-- ---------- ENUM types (idempotentes vía DO/EXCEPTION) ----------
DO $$ BEGIN CREATE TYPE appointment_status AS ENUM ('pendiente','confirmada','completada','cancelada','no_show'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE event_actor AS ENUM ('sofia','user'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE event_type AS ENUM ('sofia_classified','sofia_appointment_scheduled','sofia_escalated','sofia_error','lead_stage_changed','lead_note_added','lead_assigned','appointment_created','lead_created','appointment_approved','appointment_rejected'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE lead_channel AS ENUM ('whatsapp','telegram','web','facebook','instagram','directo','recomendado'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE lead_classification AS ENUM ('calificado','potencial','no_compatible'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE lead_nivel AS ENUM ('maternal','kinder','primaria','secundaria','prepa'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE lead_source AS ENUM ('sofia_ai','form_web','manual','import'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE lead_stage AS ENUM ('contacto_inicial','filtro_completado','cita_agendada','visita_realizada','papeleria_entregada','proceso_iniciado','descartado'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------- app_users ----------
CREATE TABLE IF NOT EXISTS app_users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    full_name     TEXT,
    role          TEXT NOT NULL DEFAULT 'staff',
    active        BOOLEAN NOT NULL DEFAULT true,
    last_login    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- leads (pre-007: sin child_grade) ----------
CREATE TABLE IF NOT EXISTS leads (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_name             TEXT NOT NULL,
    parent_phone            TEXT,
    parent_email            TEXT,
    child_name              TEXT,
    child_age               INT,
    nivel                   lead_nivel,
    channel                 lead_channel NOT NULL,
    classification          lead_classification,
    stage                   lead_stage NOT NULL DEFAULT 'contacto_inicial',
    source                  lead_source NOT NULL DEFAULT 'sofia_ai',
    sofia_active            BOOLEAN NOT NULL DEFAULT true,
    sofia_escalated         BOOLEAN NOT NULL DEFAULT false,
    sofia_suggestion        TEXT,
    assigned_to             BIGINT REFERENCES app_users(id) ON DELETE SET NULL,
    conversation_session_id TEXT,
    notes                   TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- appointments (pre-006: sin campus_id) ----------
CREATE TABLE IF NOT EXISTS appointments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id      BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    fecha_hora   TIMESTAMPTZ NOT NULL,
    duracion_min INT NOT NULL DEFAULT 60,
    status       appointment_status NOT NULL DEFAULT 'pendiente',
    notas        TEXT,
    created_by   BIGINT REFERENCES app_users(id) ON DELETE SET NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- activity_events ----------
CREATE TABLE IF NOT EXISTS activity_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type  event_type NOT NULL,
    actor_type  event_actor NOT NULL,
    actor_id    UUID,
    lead_id     BIGINT REFERENCES leads(id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    metadata    JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_leads_session ON leads(conversation_session_id);
CREATE INDEX IF NOT EXISTS idx_appointments_lead ON appointments(lead_id);
CREATE INDEX IF NOT EXISTS idx_activity_events_lead ON activity_events(lead_id);

-- ---------- KB vectorial: documents_maple + RPC match_documents ----------
-- También legacy (creadas a mano en prod). pgvector con dimensión 1536
-- (text-embedding-3-small). En prod el RPC apunta a una tabla `documents`
-- inexistente y el agente usa el fallback PostgREST; aquí lo creamos
-- correctamente sobre `documents_maple` para que el RPC funcione en QA.
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS documents_maple (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content   TEXT,
    metadata  JSONB,
    embedding VECTOR(1536)
);

CREATE OR REPLACE FUNCTION public.match_documents(
    query_embedding vector,
    match_count integer DEFAULT NULL,
    filter jsonb DEFAULT '{}'::jsonb
) RETURNS TABLE(id bigint, content text, metadata jsonb, similarity double precision)
LANGUAGE plpgsql AS $function$
#variable_conflict use_column
begin
  return query
  select
    id,
    content,
    metadata,
    1 - (documents_maple.embedding <=> query_embedding) as similarity
  from documents_maple
  where metadata @> filter
  order by documents_maple.embedding <=> query_embedding
  limit match_count;
end;
$function$;
